# Generated by Django 5.0.14 on 2026-02-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('neutral', 'Neutral Site')], max_length=10)),
                ('weather', models.CharField(choices=[('clear', 'Clear'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('windy', 'Windy'), ('hot', 'Hot (>85°F)'), ('cold', 'Cold (<40°F)')], max_length=10)),
                ('field_condition', models.CharField(choices=[('turf', 'Artificial Turf'), ('grass', 'Natural Grass'), ('wet', 'Wet/Muddy')], max_length=10)),
                ('team_score', models.PositiveSmallIntegerField(default=0)),
                ('opponent_score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='teams.season')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuarterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField()),
                ('team_score', models.PositiveSmallIntegerField(default=0)),
                ('opponent_score', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_scores', to='games.game')),
            ],
            options={
                'db_table': 'quarter_scores',
                'ordering': ['quarter'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'date'], name='games_season__6ec7ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quarterscore',
            unique_together={('game', 'quarter')},
        ),
    ]
