# Generated by Django 5.0.14 on 2026-07-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.PositiveSmallIntegerField(default=1)),
                ('down', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ball_position', models.SmallIntegerField(blank=True, help_text='Yard line (-50 to 50, negative = own territory)', null=True)),
                ('los_position', models.SmallIntegerField(blank=True, null=True)),
                ('possession', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], default='', max_length=4)),
                ('situation', models.CharField(default='pregame', max_length=20)),
                ('coin_toss_winner', models.CharField(blank=True, default='', max_length=4)),
                ('coin_toss_choice', models.CharField(blank=True, default='', max_length=8)),
                ('version', models.PositiveIntegerField(default=0)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='games.game')),
            ],
            options={
                'db_table': 'game_states',
            },
        ),
    ]
