# Generated by Django 5.0.14 on 2026-02-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSnap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='Order of this play within the game (1, 2, 3...)')),
                ('quarter', models.PositiveSmallIntegerField()),
                ('game_clock', models.DurationField(blank=True, help_text='Time remaining in quarter (e.g., 12:34)', null=True)),
                ('down', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance', models.PositiveSmallIntegerField(blank=True, help_text='Yards needed for first down', null=True)),
                ('ball_position', models.SmallIntegerField(blank=True, help_text='Yard line (-50 to 50, negative = own territory)', null=True)),
                ('formation', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snaps', to='games.game')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'snaps',
                'ordering': ['game', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('OFF', 'Offense'), ('DEF', 'Defense'), ('ST', 'Special Teams')], max_length=3)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plays',
            },
        ),
        migrations.CreateModel(
            name='DefenseSnap',
            fields=[
                ('basesnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.basesnap')),
                ('play_result', models.CharField(choices=[('TACKLE', 'Tackle'), ('TFL', 'Tackle for Loss'), ('SACK', 'Sack'), ('INT', 'Interception'), ('FREC', 'Fumble Recovery'), ('PD', 'Pass Defended'), ('PENALTY', 'Penalty')], max_length=10)),
                ('secondary_formation', models.CharField(blank=True, help_text='Defensive backfield alignment', max_length=50)),
                ('tackle_yards', models.SmallIntegerField(blank=True, help_text='Yards gained by offense on this play', null=True)),
                ('tackle_for_loss', models.BooleanField(default=False)),
                ('applied_pressure', models.BooleanField(default=False)),
                ('forced_incompletion', models.BooleanField(default=False)),
                ('interception_return_yards', models.SmallIntegerField(blank=True, null=True)),
                ('fumble_return_yards', models.SmallIntegerField(blank=True, null=True)),
                ('is_defensive_touchdown', models.BooleanField(default=False)),
                ('penalty_yards', models.SmallIntegerField(blank=True, null=True)),
                ('penalty_description', models.CharField(blank=True, max_length=100)),
                ('penalty_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_penalties', to='teams.player')),
                ('primary_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_primary_plays', to='teams.player')),
            ],
            options={
                'db_table': 'snaps_defense',
            },
            bases=('snaps.basesnap',),
        ),
        migrations.CreateModel(
            name='OffenseSnap',
            fields=[
                ('basesnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.basesnap')),
                ('play_result', models.CharField(choices=[('RUN', 'Run'), ('PASS', 'Pass'), ('SACK', 'Sack'), ('PENALTY', 'Penalty Only'), ('KNEEL', 'Kneel'), ('SPIKE', 'Spike')], max_length=10)),
                ('had_penalty', models.BooleanField(default=False)),
                ('penalty_yards', models.SmallIntegerField(blank=True, null=True)),
                ('penalty_description', models.CharField(blank=True, max_length=100)),
                ('penalty_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offense_penalties', to='teams.player')),
            ],
            options={
                'db_table': 'snaps_offense',
            },
            bases=('snaps.basesnap',),
        ),
        migrations.CreateModel(
            name='SpecialTeamsSnap',
            fields=[
                ('basesnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.basesnap')),
                ('penalty_yards', models.SmallIntegerField(blank=True, null=True)),
                ('penalty_description', models.CharField(blank=True, max_length=100)),
                ('penalty_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_penalties', to='teams.player')),
            ],
            options={
                'db_table': 'snaps_special_teams',
            },
            bases=('snaps.basesnap',),
        ),
        migrations.AddField(
            model_name='basesnap',
            name='play_called',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snaps.play'),
        ),
        migrations.CreateModel(
            name='DefenseSnapAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist_type', models.CharField(choices=[('TACKLE', 'Tackle Assist'), ('SACK', 'Sack Assist'), ('COV', 'Coverage Assist')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_assists', to='teams.player')),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='snaps.defensesnap')),
            ],
            options={
                'db_table': 'snaps_defense_assists',
            },
        ),
        migrations.CreateModel(
            name='PassPlay',
            fields=[
                ('offensesnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.offensesnap')),
                ('is_complete', models.BooleanField(default=False)),
                ('yards_gained', models.SmallIntegerField(default=0)),
                ('air_yards', models.SmallIntegerField(default=0, help_text='Yards traveled in the air before catch')),
                ('yards_after_catch', models.SmallIntegerField(default=0, help_text='YAC - yards gained after the catch')),
                ('is_touchdown', models.BooleanField(default=False)),
                ('is_first_down', models.BooleanField(default=False)),
                ('is_interception', models.BooleanField(default=False)),
                ('is_thrown_away', models.BooleanField(default=False)),
                ('was_under_pressure', models.BooleanField(default=False)),
                ('was_sacked', models.BooleanField(default=False)),
                ('sack_yards', models.SmallIntegerField(default=0, help_text='Yards lost on sack (negative number)')),
                ('fumbled', models.BooleanField(default=False)),
                ('fumble_lost', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'snaps_offense_pass',
            },
            bases=('snaps.offensesnap',),
        ),
        migrations.CreateModel(
            name='RunPlay',
            fields=[
                ('offensesnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.offensesnap')),
                ('yards_gained', models.SmallIntegerField(default=0)),
                ('is_touchdown', models.BooleanField(default=False)),
                ('is_first_down', models.BooleanField(default=False)),
                ('fumbled', models.BooleanField(default=False)),
                ('fumble_lost', models.BooleanField(default=False, help_text='True if opponent recovered')),
            ],
            options={
                'db_table': 'snaps_offense_run',
            },
            bases=('snaps.offensesnap',),
        ),
        migrations.CreateModel(
            name='ExtraPointSnap',
            fields=[
                ('specialteamssnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.specialteamssnap')),
                ('attempt_type', models.CharField(choices=[('KICK', 'PAT Kick'), ('2PT_RUN', '2-Point Run'), ('2PT_PASS', '2-Point Pass')], max_length=10)),
                ('result', models.CharField(choices=[('GOOD', 'Good'), ('MISS', 'Missed'), ('BLOCK', 'Blocked'), ('FAIL', 'Failed (2pt)')], max_length=10)),
            ],
            options={
                'db_table': 'snaps_st_extra_point',
            },
            bases=('snaps.specialteamssnap',),
        ),
        migrations.CreateModel(
            name='FieldGoalSnap',
            fields=[
                ('specialteamssnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.specialteamssnap')),
                ('kick_distance', models.PositiveSmallIntegerField(help_text='Attempt distance in yards')),
                ('result', models.CharField(choices=[('GOOD', 'Good'), ('MISS', 'Missed'), ('BLOCK', 'Blocked')], max_length=10)),
            ],
            options={
                'db_table': 'snaps_st_field_goal',
            },
            bases=('snaps.specialteamssnap',),
        ),
        migrations.CreateModel(
            name='KickoffReturnSnap',
            fields=[
                ('specialteamssnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.specialteamssnap')),
                ('return_yards', models.SmallIntegerField(default=0)),
                ('is_touchdown', models.BooleanField(default=False)),
                ('fumbled', models.BooleanField(default=False)),
                ('fumble_lost', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'snaps_st_kickoff_return',
            },
            bases=('snaps.specialteamssnap',),
        ),
        migrations.CreateModel(
            name='KickoffSnap',
            fields=[
                ('specialteamssnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.specialteamssnap')),
                ('kick_yards', models.PositiveSmallIntegerField(default=0)),
                ('is_touchback', models.BooleanField(default=False)),
                ('is_onside_kick', models.BooleanField(default=False)),
                ('onside_recovered', models.BooleanField(default=False)),
                ('out_of_bounds', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'snaps_st_kickoff',
            },
            bases=('snaps.specialteamssnap',),
        ),
        migrations.CreateModel(
            name='PuntReturnSnap',
            fields=[
                ('specialteamssnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.specialteamssnap')),
                ('return_yards', models.SmallIntegerField(default=0)),
                ('is_fair_catch', models.BooleanField(default=False)),
                ('is_touchdown', models.BooleanField(default=False)),
                ('fumbled', models.BooleanField(default=False)),
                ('fumble_lost', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'snaps_st_punt_return',
            },
            bases=('snaps.specialteamssnap',),
        ),
        migrations.CreateModel(
            name='PuntSnap',
            fields=[
                ('specialteamssnap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snaps.specialteamssnap')),
                ('punt_yards', models.PositiveSmallIntegerField(default=0)),
                ('hang_time', models.DurationField(blank=True, help_text='Ball hang time in seconds', null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_touchback', models.BooleanField(default=False)),
                ('out_of_bounds', models.BooleanField(default=False)),
                ('downed_at_yard_line', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'snaps_st_punt',
            },
            bases=('snaps.specialteamssnap',),
        ),
        migrations.AddIndex(
            model_name='basesnap',
            index=models.Index(fields=['game', 'quarter'], name='snaps_game_id_21e9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='basesnap',
            index=models.Index(fields=['game', 'sequence_number'], name='snaps_game_id_247729_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='defensesnapassist',
            unique_together={('snap', 'player', 'assist_type')},
        ),
        migrations.AddField(
            model_name='passplay',
            name='quarterback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_attempts', to='teams.player'),
        ),
        migrations.AddField(
            model_name='passplay',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='teams.player'),
        ),
        migrations.AddField(
            model_name='passplay',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='teams.player'),
        ),
        migrations.AddField(
            model_name='runplay',
            name='ball_carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rushing_attempts', to='teams.player'),
        ),
        migrations.AddField(
            model_name='runplay',
            name='fumble_recovered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rushing_fumble_recoveries', to='teams.player'),
        ),
        migrations.AddField(
            model_name='extrapointsnap',
            name='ball_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_point_carries', to='teams.player'),
        ),
        migrations.AddField(
            model_name='extrapointsnap',
            name='kicker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_point_kicks', to='teams.player'),
        ),
        migrations.AddField(
            model_name='extrapointsnap',
            name='passer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_point_passes', to='teams.player'),
        ),
        migrations.AddField(
            model_name='extrapointsnap',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_point_receptions', to='teams.player'),
        ),
        migrations.AddField(
            model_name='fieldgoalsnap',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_goal_holds', to='teams.player'),
        ),
        migrations.AddField(
            model_name='fieldgoalsnap',
            name='kicker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_goal_attempts', to='teams.player'),
        ),
        migrations.AddField(
            model_name='kickoffreturnsnap',
            name='returner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kickoff_returns', to='teams.player'),
        ),
        migrations.AddField(
            model_name='kickoffreturnsnap',
            name='tackler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kickoff_return_tackles', to='teams.player'),
        ),
        migrations.AddField(
            model_name='kickoffsnap',
            name='kicker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kickoffs', to='teams.player'),
        ),
        migrations.AddField(
            model_name='puntreturnsnap',
            name='returner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punt_returns', to='teams.player'),
        ),
        migrations.AddField(
            model_name='puntreturnsnap',
            name='tackler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punt_return_tackles', to='teams.player'),
        ),
        migrations.AddField(
            model_name='puntsnap',
            name='punter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punts', to='teams.player'),
        ),
    ]
