# Generated by Django 5.0.14 on 2026-02-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('snaps', '0002_defensesnap_opponent_play_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basesnap',
            unique_together={('game', 'sequence_number')},
        ),
    ]
