# Generated by Django 5.0.14 on 2026-07-05 16:30

from django.db import migrations, models
from django.db.models import F


def backfill_score_deltas(apps, schema_editor):
    """
    Derive score_delta_team/opponent for existing snaps using the same
    inference rules the old tracker_undo_play used. prior_state stays NULL
    for pre-existing rows; undo falls back to re-deriving state from the
    previous snap for those.
    """
    RunPlay = apps.get_model('snaps', 'RunPlay')
    PassPlay = apps.get_model('snaps', 'PassPlay')
    DefenseSnap = apps.get_model('snaps', 'DefenseSnap')
    PuntSnap = apps.get_model('snaps', 'PuntSnap')
    FieldGoalSnap = apps.get_model('snaps', 'FieldGoalSnap')
    ExtraPointSnap = apps.get_model('snaps', 'ExtraPointSnap')

    # Offensive touchdowns: +6 us.
    RunPlay.objects.filter(is_touchdown=True).update(score_delta_team=6)
    PassPlay.objects.filter(is_touchdown=True).update(score_delta_team=6)

    # Offensive safeties: +2 opponent.
    RunPlay.objects.filter(
        is_touchdown=False, fumble_lost=False, ball_position__isnull=False,
    ).annotate(
        end_pos=F('ball_position') + F('yards_gained'),
    ).filter(end_pos__lte=-50).update(score_delta_opponent=2)
    PassPlay.objects.filter(
        is_touchdown=False, is_interception=False, fumble_lost=False,
        ball_position__isnull=False, was_sacked=False,
    ).annotate(
        end_pos=F('ball_position') + F('yards_gained'),
    ).filter(end_pos__lte=-50).update(score_delta_opponent=2)
    PassPlay.objects.filter(
        is_touchdown=False, is_interception=False, fumble_lost=False,
        ball_position__isnull=False, was_sacked=True,
    ).annotate(
        end_pos=F('ball_position') + F('sack_yards'),
    ).filter(end_pos__lte=-50).update(score_delta_opponent=2)

    # Defensive touchdowns: +6 us.
    DefenseSnap.objects.filter(is_defensive_touchdown=True).update(score_delta_team=6)

    # Opponent reached our endzone on a defensive snap: +6 opponent.
    DefenseSnap.objects.filter(
        is_defensive_touchdown=False, tackle_yards__gt=0, ball_position__gt=-50,
    ).annotate(
        end_pos=F('ball_position') - F('tackle_yards'),
    ).filter(end_pos__lte=-50).update(score_delta_opponent=6)

    # Defensive safety (we pushed them into their own endzone): +2 us.
    DefenseSnap.objects.filter(
        is_defensive_touchdown=False, tackle_yards__lt=0, ball_position__isnull=False,
    ).annotate(
        end_pos=F('ball_position') - F('tackle_yards'),
    ).filter(end_pos__gte=50).update(score_delta_team=2)

    # Blocked-punt return TD: +6 us.
    PuntSnap.objects.filter(blocked_td=True).update(score_delta_team=6)

    # Made field goals: +3 us.
    FieldGoalSnap.objects.filter(result='GOOD').update(score_delta_team=3)

    # Extra points: +1 kick / +2 conversion.
    ExtraPointSnap.objects.filter(result='GOOD', attempt_type='KICK').update(score_delta_team=1)
    ExtraPointSnap.objects.filter(result='GOOD').exclude(attempt_type='KICK').update(score_delta_team=2)


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0004_puntsnap_blocked_td'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesnap',
            name='prior_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basesnap',
            name='score_delta_opponent',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basesnap',
            name='score_delta_team',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_score_deltas, migrations.RunPython.noop),
    ]
