# Generated by Django 5.0.14 on 2026-02-07 18:15

from django.db import migrations


def create_default_season(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    Season = apps.get_model("teams", "Season")

    team, _ = Team.objects.get_or_create(
        abbreviation="DEFAULT",
        defaults={"name": "My Team"},
    )
    Season.objects.get_or_create(year=2026, team=team)


def remove_default_season(apps, schema_editor):
    Season = apps.get_model("teams", "Season")
    Team = apps.get_model("teams", "Team")

    Season.objects.filter(year=2026, team__abbreviation="DEFAULT").delete()
    # Only delete the team if it has no other seasons
    team = Team.objects.filter(abbreviation="DEFAULT").first()
    if team and not team.seasons.exists():
        team.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_season, remove_default_season),
    ]
